### ISSUE TITLE
Repo Ranger failing to merge PRs

### ISSUE THREAD

**Issue by chris48s** [reporanger/ranger#120]
Hello. I've just labelled a whole bunch of PRs for repo ranger to merge. Example https://github.com/badges/shields/pull/8701 and repo ranger isn't updating or merging them.

I think the last time I saw this working was 6 days ago on https://github.com/badges/shields/pull/8685

As always, if I can provide any extra info to help then let me know. Thanks

**Comment by mfix22** [comment]
Hey @chris48s sorry about this—our db service provider detached our Redis database from our instance and we are now scrambling for alternatives. Thanks for your patience and understanding.

**Comment by mfix22** [comment]
Should be back up now. Sorry for the immense delays.

**Comment by chris48s** [comment]
Amazing - can confirm this is working. Cheers :)
